# yaml-language-server: $schema=https://raw.githubusercontent.com/SchemaStore/schemastore/master/src/schemas/json/github-workflow.json
name: Test Build Supported Verions

on:
  repository_dispatch:
    types: [game_version_update, game_version_update_patch]
  push:
    branches:
      - master
    paths:
      - '.github/workflows/test-build.yml'
      - 'src/**'
      - 'tests/**'
  pull_request:
    branches:
      - master
    # will be triggered when undrafting or requesting review
    types: [review_requested, ready_for_review]
    paths:
      - '.github/workflows/test-build.yml'
      - 'src/**'
      - 'tests/**'

env:
  # Disable the .NET logo in the console output.
  DOTNET_NOLOGO: true
  # Disable the .NET first time experience to skip caching NuGet packages and speed up the build.
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  # Disable sending .NET CLI telemetry to Microsoft.
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:

  build:
    name: Test Build Supported Verions
    runs-on: windows-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup .NET Core
      uses: actions/setup-dotnet@master
      with:
        dotnet-version: 7.0.x

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.3
      with:
        msbuild-architecture: x64

    - name: Build DiscordRichPresence for test
      run: >-
          dotnet restore src/Bannerlord.DiscordRichPresence/Bannerlord.DiscordRichPresence.csproj;
          msbuild src/Bannerlord.DiscordRichPresence/Bannerlord.DiscordRichPresence.csproj /t:ExtendedMSBuild /p:configuration=Release /p:GameFolder="$PWD/bannerlord";
      shell: pwsh
